task: uskin_gelsight

src_img: dataset/img_gen/heter/uskin_gelsight/genforce/infer/hetero/final_force/uskin_gelsight/02_25_21_14
src_force: dataset/training/hetero/force/uskin

tar_img: dataset/training/hetero/img/gelsight
tar_force: dataset/training/hetero/force/gelsight

min_max: force/config/min_max.json

checkpoint: infer/force_com/hetero/uskin_gelsight/20250305_015626/epoch_20.pth
save_dir: infer/force_com/hetero/{}

src_depth: dataset/training/hetero/depth/uskin
modulus: dataset/training/material_compensatin/hetero/cofficient

unseen: ["sphere_s", "triangle", "pacman", "cone", "wave", "torus","dots"]
test_unseen: False

#Train
train: True
train_use_checkpoint: False                 
draw_force: True
draw_use_checkpoint: False 
     
#Infer
# train: False
# train_use_checkpoint: True                 
# draw_force: True
# draw_use_checkpoint: True               

num_workers: 16
batch_size: 4
n_epoch: 20
early_stop: 20
lr: 1e-1   #train 1e-1;fine tune:1e-3
seed: 0
