task: Array-I_Array-II

src_img: dataset/Image_gen/homo/Array-II/Array-I_Array-II/01_13_07_09
src_force: dataset/training/training/homo/force/Array-I

tar_img: dataset/training/training/homo/img/npy/Array-II
tar_force: dataset/training/training/homo/force/Array-II

min_max: force/config/min_max.json

checkpoint: checkpoints/rebutal/force/Array-II/Array-I_Array-II/20250729_232638/epoch_20.pth
save_dir: checkpoints/rebutal/force/Array-II/{}

unseen: ["sphere_s", "triangle", "pacman", "cone", "wave", "torus"]
test_unseen: False

#Train
train: True
train_use_checkpoint: True                 
draw_force: True
draw_use_checkpoint: False 
     
#Infer
# train: False
# train_use_checkpoint: True                 
# draw_force: True
# draw_use_checkpoint: True               

num_workers: 16
batch_size: 1
n_epoch: 20
early_stop: 20
lr: 1e-3   #train 1e-1;fine tune:1e-3
seed: 0

